language: python
python:
- '3.3'
- pypy
before_install: 
install:
- pip install "Nikola[extras]"
before_script: 
script:
- echo "EPIC WIN"
notifications:
  slack:
    secure: SlRkSEKTHl8cNKY63mp+2rFWVG+NvuUyo1Fwzd/3WaH+ghfFlheYkckZHKti9SRdQO+JBWba6bYoX7uEJAD+zKko1Ej6XU2b0t1MGTDxLj5aFbWO+XRNDztSqaf98K7T63wwN9ErlRM0LTQ4nPPvWyl22uiJbkS/jWvzozutvZToi7GLfJrvhcSJ4Su3qaouhHohqOSXRRtyqBvgwqqywZayGVpMrUv4aj+NyFG7il9FM9hdYZ5+ha5wL9tI4664m0NyonsUIxxyjjS9Oz+GAbvNshMoHuxrHFz9kKhKU9BFP5GzsR7ZPxZS0idJfeFtktygp9+icU6EzhVyAUpx/dxATj66xtnnRE40vmnzLwQkUOg/G4lb6frWq8AGr7AU/Rr8lOWiq7JH0XzRD9QTUOVAtvIQ3GYPYjyQ6t3w9vJkcOOnJVRldvK5cKiO6n9nnH58mufM7h4l5jU8aIANfhwj+/U4XzLKJcmhJxS4ZHZitpm+BXfdBymblkm6bAdlyCVC2GJ9tAFFHxFaT7884VmPAumhe+Gh8jbzhPNwrrZlXiVqcGsuZQuZYrpO85IDINagg3Jc0F/obsUyEYzoLNpVJtN9i5/X+Gcs00iFH5osqaHH2+jApeWi3CrFRwKvv2tRtlz7bag2cRmO+2bMmqs0NbJXrW3glN/CuxKfPSA=
