language: python
python:
- '3.3'
- pypy
before_install: 
install:
- pip install "Nikola[extras]"
before_script: 
notifications:
  slack:
    secure: UOuyqUgeZQ2Tk/Rv7hQzbHZlpF6GHiNCS4v+zDvL0llfA0233mMoZKbQBegqmU45pxNSZq1LLpKmjHvz7JNMYUhynQ36zH2gDm8iBtFknTCBRC8RaxyXXRV89rYjJO/pSqNHPaRxUQVTvxqW43mw+dsrrwYA6acYxMMk2KXEjLY3esvXBqPM0anzau8ZFXRtCTPWtmgipCeHZjearyfP0xP7CMRc0lWxJddTFLFXkETColUbTPZ/nz02B76exvPSqc5NooCDVjxxo4J/lXpXG9HJapK0rN9Nxe6mkkrR2r3mjiDaGojMY4XJ8Ho+v5hQUGih41H0y8vl3QFSJXqgsEiJN0Hnge/RU9G9W9mXkH2dk486KZvQvBca0wyaFzZOjWOUnbVx+BXayLRODEomuShfQduu1xoj5krx5MgZR5IQGqm0Kfg8oZCwvad4PhdOny8U5LyWGFw+JFOD3E9KOUYXyLcrd9rWKsRXqcOCHZKDcYBN13SXsq0l24Mpg1yVrU1iYcBc3lHS9QtZUmtvysXzlw6vcOu0Ua5cJlIAja0d62s4kRvK1YBNna8mK/eC1fUXgn7YMEx43ocMFf04cE5N5DpPL35RHJZXAvM8FzTSKLzKxkEHWtblYWMQCN336+RzwQMuJcRr4d7TJrnGhw78I9T3ZufLIIWHhZ1Bpxw=
